import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import { Providers } from './components/Providers';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog With Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={` ${inter.className} backdrop-blur p-4`}>
        <Providers>
          <Navbar />
          <main className='mx-auto px-2 sm:px-3 lg:px-4'>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
